### ISSUE TITLE
"unknown option 'required' for configuration parameter: host"

### ISSUE THREAD

**Issue by monson** [cmeerbeek/fluent-plugin-splunkhec#3] opened 2017-02-14 18:30 UTC
"unknown option 'required' for configuration parameter: host"
Getting the following error when I try to use this plugin.

2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:696:block in main_process: unexpected error error_class=ArgumentError error="unknown option 'required' for configuration parameter: host"
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:244:in `block in config_parameter_option_validate!'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:233:in `each_key'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:233:in `config_parameter_option_validate!'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:250:in `parameter_configuration'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/config/configure_proxy.rb:318:in `config_param'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/configurable.rb:157:in `config_param'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/compat/propagate_default.rb:36:in `call'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/compat/propagate_default.rb:36:in `config_param'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluent-plugin-splunkhec-1.0.0/lib/fluent/plugin/out_splunkhec.rb:10:in `<class:SplunkHECOutput>'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluent-plugin-splunkhec-1.0.0/lib/fluent/plugin/out_splunkhec.rb:6:in `<module:Fluent>'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluent-plugin-splunkhec-1.0.0/lib/fluent/plugin/out_splunkhec.rb:5:in `<top (required)>'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/registry.rb:102:in `block in search'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/registry.rb:99:in `each'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/registry.rb:99:in `search'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/registry.rb:44:in `lookup'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:146:in `new_impl'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:104:in `new_output'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin/multi_output.rb:71:in `block in configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin/multi_output.rb:62:in `each'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin/multi_output.rb:62:in `configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/plugin.rb:164:in `configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:128:in `add_match'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:71:in `block in configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:64:in `each'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/agent.rb:64:in `configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/root_agent.rb:86:in `configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:117:in `configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/engine.rb:91:in `run_configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:743:in `run_configure'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:494:in `block in run_worker'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:671:in `call'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:671:in `main_process'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/supervisor.rb:490:in `run_worker'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/lib/fluent/command/fluentd.rb:300:in `<top (required)>'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/lib/ruby/gems/2.2.0/gems/fluentd-0.14.12/bin/fluentd:5:in `<top (required)>'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/bin/fluentd:23:in `load'
  2017-02-14 10:50:08 -0700 [error]: #0 fluent/supervisor.rb:670:main_process: /usr/local/bin/fluentd:23:in `<main>'

**Comment by cmeerbeek** [comment] 2017-02-14 19:45
@monson thanks for posting this issue. Can you post your config? If you want to email me that is also possible.

**Comment by monson** [comment] 2017-02-14 20:14
<match debug.**>
@type copy 
<store>
  @type kafka_buffered
  # list of seed brokers
  brokers localhost:9092
  # buffer settings
  buffer_type file
  buffer_path /var/log/td-agent/buffer/td
  flush_interval 3s
  # topic settings
  default_topic test
  # data type settings
  output_data_type json
  compression_codec gzip
  # producer settings
  max_send_retries 1
  required_acks -1
</store>
<store>
  @type splunkhec
  host *******
  token ******
  index pas
  event_host kube 
</store>
</match>

i use copy plugin and splunk plugin is a store

**Comment by cmeerbeek** [comment] 2017-02-14 20:21
Do you use fluentd or td-agent? Which version?

I have time on Thursday to look into this. Will update this issue
accordingly.

-----------------------

Coen Meerbeek

Social Networks: @cmeerbeek
Skype / IM: cmeerbeek
Mobile: +316 250 217 66

"In the Modern Meeting, the decision is King. All hail the King!"

**Comment by monson** [comment] 2017-02-14 20:23
i use fluentd

fluentd 0.14.12

here is the config. I use copy plugin

<store>
  @type splunkhec
  host *******
  token ******
  index pas
  event_host kube

</store>

**Comment by cmeerbeek** [comment] 2017-02-16 11:28
Hi @monson,
I think I've fixed the problem you are having. Version 1.0.1 is pushed to rubuygems.org.
Can you update you're plugin and try again?

**Comment by monson** [comment] 2017-02-16 21:54
i tried ..having the same issue
2017-02-16 14:52:04 -0700 [info]: serverengine/multi_process_server.rb:136:alive?: Worker 0 finished unexpectedly with status 1
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-copy_ex' version '0.0.3'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-kafka' version '0.5.1'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-splunk-ex' version '1.0.2'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-splunk-http-eventcollector' version '0.0.4'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-splunkapi' version '0.2.0'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluent-plugin-splunkhec' version '1.0.1'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluentd' version '0.14.12'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluentd' version '0.12.32'
2017-02-16 14:52:04 -0700 [info]: fluent/engine.rb:114:block in configure: gem 'fluentd' version '0.10.62'
2017-02-16 14:52:04 -0700 [info]: fluent/agent.rb:124:add_match: adding match pattern="system.**" type="forward"
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered output plugin 'forward'
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered buffer plugin 'memory'
2017-02-16 14:52:04 -0700 [info]: #0 plugin/out_forward.rb:187:block in configure: adding forwarding server '192.168.0.12:24224' host="192.168.0.12" port=24224 weight=60 plugin_id="object:3fdd694dba80"
2017-02-16 14:52:04 -0700 [info]: #0 [forward_output] adding forwarding server '192.168.0.11:24224' host="192.168.0.11" port=24224 weight=60 plugin_id="forward_output"
2017-02-16 14:52:04 -0700 [info]: fluent/agent.rb:124:add_match: adding match pattern="debug.**" type="copy"
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered output plugin 'copy'
2017-02-16 14:52:04 -0700 [debug]: #0 plugin/multi_output.rb:69:block in configure: adding store type="kafka_buffered"
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered output plugin 'kafka_buffered'
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered buffer plugin 'file'
2017-02-16 14:52:04 -0700 [info]: #0 plugin/out_kafka_buffered.rb:124:configure: brokers has been set directly: ["localhost:9092"]
2017-02-16 14:52:04 -0700 [debug]: #0 plugin/multi_output.rb:69:block in configure: adding store type="splunkhec"
2017-02-16 14:52:04 -0700 [trace]: #0 fluent/plugin.rb:140:register_impl: registered output plugin 'splunkhec'
2017-02-16 14:52:04 -0700 [error]: #0 fluent/supervisor.rb:696:block in main_process: unexpected error error_class=ArgumentError error="unknown option 'required' for configuration parameter: host"

**Comment by cmeerbeek** [comment] 2017-02-17 10:11
Hi @monson. This is challenging. No matter what I try, I can't reproduce the error.
I've tried fluentd v0.12 and v0.14. I've used the copy plugin. It works all the time.

Is it possible for you to sent me the full conf file without modifications? My email-address is in my GitHub profile if you don't want to post it here.

Also; can you try to install a fresh box with fluentd and the necessary plugins without any other Splunk plugins? Try again and sent me the result.

**Comment by cmeerbeek** [comment] 2017-05-05 07:45
Via email confirmed this issue is local system related and can be closed.

**Comment by jad007** [comment] 2017-08-03 21:57
Hi @cmeerbeek, I seem to be having a problem similar to what was reported here, running fluentd in a docker container.

config:
```<match **>
   @type splunkhec
   host "<splunkhost.com>"
   port 443
   token <token>
   protocol https
   index fluentd
   event_host jduncan
   send_event_as_json true
</match>
```

Dockerfile used (you can also see the other plugins installed):

```
FROM fluent/fluentd:v0.14-debian
MAINTAINER Jared Duncan

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install \
        fluent-plugin-secure-forward \
        fluent-plugin-systemd:0.3.0 \
        fluent-plugin-record-reformer \
        fluent-plugin-splunkhec \
        fluent-plugin-kubernetes_metadata_filter \
        fluent-plugin-rewrite-tag-filter \
        fluent-plugin-multi-format-parser \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

ENTRYPOINT [ "fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins" ]
```

Error:

```
2017-08-03 21:42:32 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/tmp.conf"
/var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/config/configure_proxy.rb:244:in `block in config_parameter_option_validate!': unknown option 'required' for configuration parameter: host (ArgumentError)
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/config/configure_proxy.rb:233:in `each_key'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/config/configure_proxy.rb:233:in `config_parameter_option_validate!'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/config/configure_proxy.rb:250:in `parameter_configuration'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/config/configure_proxy.rb:318:in `config_param'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/configurable.rb:157:in `config_param'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/compat/propagate_default.rb:36:in `call'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/compat/propagate_default.rb:36:in `config_param'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.0.1/lib/fluent/plugin/out_splunkhec.rb:10:in `<class:SplunkHECOutput>'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.0.1/lib/fluent/plugin/out_splunkhec.rb:6:in `<module:Fluent>'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.0.1/lib/fluent/plugin/out_splunkhec.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/plugin.rb:104:in `new_output'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/agent.rb:128:in `add_match'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/agent.rb:72:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/agent.rb:64:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/agent.rb:64:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/root_agent.rb:112:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:768:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:551:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:569:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/supervisor.rb:474:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.20/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'
```

**Comment by cmeerbeek** [comment] 2017-08-04 12:49
Hi @jad007,

Is it possible you are using an old version of the plugin?
I've removed the required field in the parameter definition.

A couple of seconds ago I pushed version 1.1 to GitHub.

**Comment by jad007** [comment] 2017-08-04 14:22
Using the new 1.1 version works for me.

**Comment by cmeerbeek** [comment] 2017-08-04 14:26
Great to hear. Will close this issue!

**Closed as completed by cmeerbeek** 2017-08-04 14:26 UTC

**Comment by xeor** [comment] 2017-08-11 20:13
Why is gem install still giving out `fluent-plugin-splunkhec-1.0.1`? This will still bite you install it manually from github.. :(
